/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tp_duo_mega_demineur;

/**
 *
 * @author Alexander
 */
public class Ecran_Défaite extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ecran_Défaite.class.getName());

    /**
     * Creates new form Ecran_Défaite
     */
    public Ecran_Défaite() {
        initComponents();
        setLocationRelativeTo(null);
        setImageToLabelKeepRatio(Image_Perdu_label, "/Images/Perdu.jpg");
        setImageToLabelKeepRatio(You_died_label, "/Images/You_Died.png");
    }
    private void setImageToLabelKeepRatio(javax.swing.JLabel label, String resourcePath) {
        java.net.URL url = getClass().getResource(resourcePath);
        if (url == null) {
            System.err.println("Ressource introuvable : " + resourcePath);
            return;
        }
        javax.swing.ImageIcon originalIcon = new javax.swing.ImageIcon(url);
        if (label.getWidth() <= 0 || label.getHeight() <= 0) {
            label.setIcon(originalIcon); // icône provisoire
            label.addComponentListener(new java.awt.event.ComponentAdapter() {
                @Override
                public void componentResized(java.awt.event.ComponentEvent e) {
                    scaleAndSetIconKeepRatio(label, originalIcon);
                }
                @Override
                public void componentShown(java.awt.event.ComponentEvent e) {
                    scaleAndSetIconKeepRatio(label, originalIcon);
                }
            });
            return;
        }
        scaleAndSetIconKeepRatio(label, originalIcon);
    }
    private void scaleAndSetIconKeepRatio(javax.swing.JLabel label, javax.swing.ImageIcon originalIcon) {
        int labelW = label.getWidth();
        int labelH = label.getHeight();
        if (labelW <= 0 || labelH <= 0) {
            return;
        }
        int imgW = originalIcon.getIconWidth();
        int imgH = originalIcon.getIconHeight();
        double scale = Math.min((double) labelW / imgW, (double) labelH / imgH);
        int newW = Math.max(1, (int) (imgW * scale));
        int newH = Math.max(1, (int) (imgH * scale));
        java.awt.Image scaled = originalIcon.getImage()
                .getScaledInstance(newW, newH, java.awt.Image.SCALE_SMOOTH);
        label.setIcon(new javax.swing.ImageIcon(scaled));
        label.setText("");
        label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Défaite_label = new javax.swing.JLabel();
        Retour_EcranTitre_Défaite_bouton = new javax.swing.JButton();
        RelancerPartie_Défaite_bouton = new javax.swing.JButton();
        QuitterDéfaite_bouton = new javax.swing.JButton();
        Image_Perdu_label = new javax.swing.JLabel();
        You_died_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Défaite_label.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        Défaite_label.setText("Défaite...");
        getContentPane().add(Défaite_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, -1, -1));

        Retour_EcranTitre_Défaite_bouton.setText("Ecran Titre");
        Retour_EcranTitre_Défaite_bouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Retour_EcranTitre_Défaite_boutonActionPerformed(evt);
            }
        });
        getContentPane().add(Retour_EcranTitre_Défaite_bouton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, -1, -1));

        RelancerPartie_Défaite_bouton.setText("Relancer une partie");
        RelancerPartie_Défaite_bouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelancerPartie_Défaite_boutonActionPerformed(evt);
            }
        });
        getContentPane().add(RelancerPartie_Défaite_bouton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 490, -1, -1));

        QuitterDéfaite_bouton.setText("Quitter");
        QuitterDéfaite_bouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitterDéfaite_boutonActionPerformed(evt);
            }
        });
        getContentPane().add(QuitterDéfaite_bouton, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 490, -1, -1));

        Image_Perdu_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Perdu.jpg"))); // NOI18N
        getContentPane().add(Image_Perdu_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 290, 220));

        You_died_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/You_Died.png"))); // NOI18N
        You_died_label.setText("You_died_label");
        getContentPane().add(You_died_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 440, 140));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Retour_EcranTitre_Défaite_boutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Retour_EcranTitre_Défaite_boutonActionPerformed
        // TODO add your handling code here:
        Ecran_Titre accueil = new Ecran_Titre();
        accueil.setLocationRelativeTo(this); 
        accueil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Retour_EcranTitre_Défaite_boutonActionPerformed

    private void RelancerPartie_Défaite_boutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelancerPartie_Défaite_boutonActionPerformed
        // TODO add your handling code here:
        Ecran_Jeu accueil = new Ecran_Jeu(10,10,5);
        accueil.setLocationRelativeTo(this); 
        accueil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RelancerPartie_Défaite_boutonActionPerformed

    private void QuitterDéfaite_boutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitterDéfaite_boutonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_QuitterDéfaite_boutonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Ecran_Défaite().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Défaite_label;
    private javax.swing.JLabel Image_Perdu_label;
    private javax.swing.JButton QuitterDéfaite_bouton;
    private javax.swing.JButton RelancerPartie_Défaite_bouton;
    private javax.swing.JButton Retour_EcranTitre_Défaite_bouton;
    private javax.swing.JLabel You_died_label;
    // End of variables declaration//GEN-END:variables
}
