/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tp_duo_mega_demineur;

import Class_Metier.Cellule;
import Class_Metier.GrilleDeJeu;
import Class_Metier.JBouton_better;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JFrame;

/**
 *
 * @author Alexander
 */
public class Ecran_Jeu extends javax.swing.JFrame {
    JFrame a;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ecran_Jeu.class.getName());
    int nblignes ;
    int nbcolones;
    int nbbombes;
    /**
     * Creates new form Ecran_Jeu
     */
    public Ecran_Jeu(int nblignes,int nbcolones, int nbbombes) {
        a=this;
        this.nblignes = nblignes;
        this.nbcolones = nbcolones;
        this.nbbombes = nbbombes;
        GrilleDeJeu game = new GrilleDeJeu(this.nblignes,this.nbcolones, this.nbbombes);
        initComponents();

        game.placerBombesAleatoirement();
        game.calculerBombesAdjacentes();
        game.placerkitDeminage();

        int nbLignes = this.nblignes;
        int nbColonnes = this.nbcolones;

        FenêtrePrincipal_Jeu.setLayout(new GridLayout(nbLignes, nbColonnes));
        for (int i = 0; i < nbLignes; i++) {
            for (int j = 0; j < nbColonnes; j++) {
                Cellule c = game.getgrille()[i][j];
                JBouton_better bouton_cellule = new JBouton_better(i, j, c);
                final int x = i;
                final int y = j;
                ActionListener ecouteurClick = new ActionListener() {

                    @Override
                    public void actionPerformed(ActionEvent e) {
                        
                        game.InteractionCellule(x, y);
                        
                        System.out.println(game);
                        FenêtrePrincipal_Jeu.repaint();
                        if (game.toutesCellulesRevelees()=="perdu"){
                            Ecran_Défaite defaite = new Ecran_Défaite();
                            defaite.setLocationRelativeTo(a);
                            defaite.setVisible(true);
                            a.dispose();
                                
                            
                        }
                        if(game.toutesCellulesRevelees()=="gagné"){
                           Ecran_Victoire victoire = new Ecran_Victoire();
                            victoire.setLocationRelativeTo(a);
                            victoire.setVisible(true);
                            a.dispose(); 
                        }
                        else{
                            nb_de_vie.setText(game.toutesCellulesRevelees());
                            nb_kit_desamorcage.setText(game.getnbkit() +"");
                            if(game.InteractionCellule(x, y).equals("K")){
                               txt_info_possession_kit.setText("Decouvert : OUI ");
                            }
                        }
                    }
                };
                bouton_cellule.addActionListener(ecouteurClick);
                FenêtrePrincipal_Jeu.add(bouton_cellule); // ajout au Jpanel PanneauGrille 
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Retour_EcranTitre_Jeu_bouton = new javax.swing.JButton();
        Quitter_Jeu_bouton = new javax.swing.JButton();
        Titre_Jeu_label = new javax.swing.JLabel();
        FenêtrePrincipal_Jeu = new javax.swing.JPanel();
        txt_nb_de_vie = new javax.swing.JLabel();
        nb_de_vie = new javax.swing.JLabel();
        txt_Kit_desamorcage = new javax.swing.JLabel();
        nb_kit_desamorcage = new javax.swing.JLabel();
        txt_info_possession_kit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Retour_EcranTitre_Jeu_bouton.setText("Ecran Titre");
        Retour_EcranTitre_Jeu_bouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Retour_EcranTitre_Jeu_boutonActionPerformed(evt);
            }
        });
        getContentPane().add(Retour_EcranTitre_Jeu_bouton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 520, -1, -1));

        Quitter_Jeu_bouton.setText("Quitter");
        Quitter_Jeu_bouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Quitter_Jeu_boutonActionPerformed(evt);
            }
        });
        getContentPane().add(Quitter_Jeu_bouton, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 520, -1, -1));

        Titre_Jeu_label.setFont(new java.awt.Font("Snap ITC", 1, 48)); // NOI18N
        Titre_Jeu_label.setText("JEU");
        getContentPane().add(Titre_Jeu_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));

        FenêtrePrincipal_Jeu.setBackground(new java.awt.Color(255, 0, 0));
        FenêtrePrincipal_Jeu.setPreferredSize(new java.awt.Dimension(400, 400));

        javax.swing.GroupLayout FenêtrePrincipal_JeuLayout = new javax.swing.GroupLayout(FenêtrePrincipal_Jeu);
        FenêtrePrincipal_Jeu.setLayout(FenêtrePrincipal_JeuLayout);
        FenêtrePrincipal_JeuLayout.setHorizontalGroup(
            FenêtrePrincipal_JeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        FenêtrePrincipal_JeuLayout.setVerticalGroup(
            FenêtrePrincipal_JeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        getContentPane().add(FenêtrePrincipal_Jeu, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, -1));

        txt_nb_de_vie.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        txt_nb_de_vie.setText("Vies :");
        txt_nb_de_vie.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 51)));
        getContentPane().add(txt_nb_de_vie, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 90, 50));

        nb_de_vie.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        nb_de_vie.setText("3");
        getContentPane().add(nb_de_vie, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 40, 50));

        txt_Kit_desamorcage.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        txt_Kit_desamorcage.setText("Kit :");
        txt_Kit_desamorcage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        getContentPane().add(txt_Kit_desamorcage, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 90, 30));

        nb_kit_desamorcage.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        nb_kit_desamorcage.setText("0");
        getContentPane().add(nb_kit_desamorcage, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 30, 50));

        txt_info_possession_kit.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        txt_info_possession_kit.setText("Decouvert : NON");
        txt_info_possession_kit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 51)));
        getContentPane().add(txt_info_possession_kit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Retour_EcranTitre_Jeu_boutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Retour_EcranTitre_Jeu_boutonActionPerformed
        // TODO add your handling code here:
        Ecran_Titre accueil = new Ecran_Titre();
        accueil.setLocationRelativeTo(this);
        accueil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Retour_EcranTitre_Jeu_boutonActionPerformed

    private void Quitter_Jeu_boutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Quitter_Jeu_boutonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_Quitter_Jeu_boutonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Ecran_Jeu(10,10,5).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FenêtrePrincipal_Jeu;
    private javax.swing.JButton Quitter_Jeu_bouton;
    private javax.swing.JButton Retour_EcranTitre_Jeu_bouton;
    private javax.swing.JLabel Titre_Jeu_label;
    private javax.swing.JLabel nb_de_vie;
    private javax.swing.JLabel nb_kit_desamorcage;
    private javax.swing.JLabel txt_Kit_desamorcage;
    private javax.swing.JLabel txt_info_possession_kit;
    private javax.swing.JLabel txt_nb_de_vie;
    // End of variables declaration//GEN-END:variables
}
