/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tp_duo_mega_demineur;

import javax.swing.JOptionPane;

/**
 *
 * @author Alexander
 */
public class Ecran_Titre extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ecran_Titre.class.getName());

    /**
     * Creates new form Ecran_Titre
     */
    public Ecran_Titre() {
        initComponents();
        setLocationRelativeTo(null);
        setImageToLabelKeepRatio(Image_EcranTitre_label, "/Images/EPF_logo_2021.png");
        setImageToLabelKeepRatio(Image_logo_label, "/Images/Démineur.png");
    }
    private void setImageToLabelKeepRatio(javax.swing.JLabel label, String resourcePath) {
        java.net.URL url = getClass().getResource(resourcePath);
        if (url == null) {
            System.err.println("Ressource introuvable : " + resourcePath);
            return;
        }
        javax.swing.ImageIcon originalIcon = new javax.swing.ImageIcon(url);
        if (label.getWidth() <= 0 || label.getHeight() <= 0) {
            label.setIcon(originalIcon); // icône provisoire
            label.addComponentListener(new java.awt.event.ComponentAdapter() {
                @Override
                public void componentResized(java.awt.event.ComponentEvent e) {
                    scaleAndSetIconKeepRatio(label, originalIcon);
                }

                @Override
                public void componentShown(java.awt.event.ComponentEvent e) {
                    scaleAndSetIconKeepRatio(label, originalIcon);
                }
            });
            return;
        }
        scaleAndSetIconKeepRatio(label, originalIcon);
    }
    private void scaleAndSetIconKeepRatio(javax.swing.JLabel label, javax.swing.ImageIcon originalIcon) {
        int labelW = label.getWidth();
        int labelH = label.getHeight();
        if (labelW <= 0 || labelH <= 0) {
            return;
        }
        int imgW = originalIcon.getIconWidth();
        int imgH = originalIcon.getIconHeight();
        double scale = Math.min((double) labelW / imgW, (double) labelH / imgH);
        int newW = Math.max(1, (int) (imgW * scale));
        int newH = Math.max(1, (int) (imgH * scale));
        java.awt.Image scaled = originalIcon.getImage()
                .getScaledInstance(newW, newH, java.awt.Image.SCALE_SMOOTH);
        label.setIcon(new javax.swing.ImageIcon(scaled));
        label.setText("");
        label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titre_label = new javax.swing.JLabel();
        Jouer_EcranTitre_bouton = new javax.swing.JButton();
        Quitter_EcranTitre_bouton = new javax.swing.JButton();
        Nb_lignes_label = new javax.swing.JLabel();
        Nb_colones_label = new javax.swing.JLabel();
        Nb_bombes_label = new javax.swing.JLabel();
        Nb_lignes_spinner = new javax.swing.JSpinner();
        Nb_colones_spinner = new javax.swing.JSpinner();
        Nb_bombes_spinner = new javax.swing.JSpinner();
        Image_EcranTitre_label = new javax.swing.JLabel();
        Image_logo_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titre_label.setFont(new java.awt.Font("Stencil", 1, 48)); // NOI18N
        Titre_label.setText("Mega Démineur");
        getContentPane().add(Titre_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, 75));

        Jouer_EcranTitre_bouton.setText("Jouer");
        Jouer_EcranTitre_bouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jouer_EcranTitre_boutonActionPerformed(evt);
            }
        });
        getContentPane().add(Jouer_EcranTitre_bouton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, -1, -1));

        Quitter_EcranTitre_bouton.setText("Quitter");
        Quitter_EcranTitre_bouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Quitter_EcranTitre_boutonActionPerformed(evt);
            }
        });
        getContentPane().add(Quitter_EcranTitre_bouton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 480, -1, -1));

        Nb_lignes_label.setText("Nombre de Lignes :");
        getContentPane().add(Nb_lignes_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, -1, -1));

        Nb_colones_label.setText("Nombre de colones :");
        getContentPane().add(Nb_colones_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, -1, -1));

        Nb_bombes_label.setText("Nombre de bombes :");
        getContentPane().add(Nb_bombes_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, -1, -1));
        getContentPane().add(Nb_lignes_spinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, 80, -1));
        getContentPane().add(Nb_colones_spinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, 80, -1));
        getContentPane().add(Nb_bombes_spinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, 80, -1));

        Image_EcranTitre_label.setBackground(new java.awt.Color(255, 255, 255));
        Image_EcranTitre_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/EPF_logo_2021.png"))); // NOI18N
        Image_EcranTitre_label.setText("Image Logo EPF");
        getContentPane().add(Image_EcranTitre_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 110, 90));

        Image_logo_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Démineur.png"))); // NOI18N
        Image_logo_label.setText("Logo_Jeu");
        getContentPane().add(Image_logo_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 300, 150));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void Jouer_EcranTitre_boutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jouer_EcranTitre_boutonActionPerformed
        // TODO add your handling code here:
        int nbLignes = (Integer) Nb_lignes_spinner.getValue();
        int nbColonnes = (Integer) Nb_colones_spinner.getValue();
        int nbBombes = (Integer) Nb_bombes_spinner.getValue();
        if (nbLignes <= 0 || nbColonnes <= 0 || nbBombes <= 0) {
            JOptionPane.showMessageDialog(
                    this,
                    "Veuillez choisir au moins 1 pour chaque composante (lignes, colonnes et bombes).",
                    "Erreur de configuration",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        if (nbBombes > nbLignes*nbColonnes) {
            JOptionPane.showMessageDialog(
                    this,
                    "Il y a trop de bombes pour le nombre de cases disponible.",
                    "Erreur de configuration",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        Ecran_Jeu accueil = new Ecran_Jeu();
        accueil.setLocationRelativeTo(this);
        accueil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Jouer_EcranTitre_boutonActionPerformed

    private void Quitter_EcranTitre_boutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Quitter_EcranTitre_boutonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_Quitter_EcranTitre_boutonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Ecran_Titre().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Image_EcranTitre_label;
    private javax.swing.JLabel Image_logo_label;
    private javax.swing.JButton Jouer_EcranTitre_bouton;
    private javax.swing.JLabel Nb_bombes_label;
    private javax.swing.JSpinner Nb_bombes_spinner;
    private javax.swing.JLabel Nb_colones_label;
    private javax.swing.JSpinner Nb_colones_spinner;
    private javax.swing.JLabel Nb_lignes_label;
    private javax.swing.JSpinner Nb_lignes_spinner;
    private javax.swing.JButton Quitter_EcranTitre_bouton;
    private javax.swing.JLabel Titre_label;
    // End of variables declaration//GEN-END:variables
}
