/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tp_duo_mega_demineur;

/**
 *
 * @author Alexander
 */
public class Ecran_Titre extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ecran_Titre.class.getName());

    /**
     * Creates new form Ecran_Titre
     */
    public Ecran_Titre() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titre_label = new javax.swing.JLabel();
        Jouer_EcranTitre_bouton = new javax.swing.JButton();
        Quitter_EcranTitre_bouton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Titre_label.setFont(new java.awt.Font("Stencil", 1, 48)); // NOI18N
        Titre_label.setText("Mega Démineur");

        Jouer_EcranTitre_bouton.setText("Jouer");
        Jouer_EcranTitre_bouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jouer_EcranTitre_boutonActionPerformed(evt);
            }
        });

        Quitter_EcranTitre_bouton.setText("Quitter");
        Quitter_EcranTitre_bouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Quitter_EcranTitre_boutonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Jouer_EcranTitre_bouton)
                        .addGap(254, 254, 254)
                        .addComponent(Quitter_EcranTitre_bouton))
                    .addComponent(Titre_label))
                .addGap(128, 128, 128))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(Titre_label, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 229, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jouer_EcranTitre_bouton)
                    .addComponent(Quitter_EcranTitre_bouton))
                .addGap(126, 126, 126))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Jouer_EcranTitre_boutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jouer_EcranTitre_boutonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jouer_EcranTitre_boutonActionPerformed

    private void Quitter_EcranTitre_boutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Quitter_EcranTitre_boutonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Quitter_EcranTitre_boutonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Ecran_Titre().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jouer_EcranTitre_bouton;
    private javax.swing.JButton Quitter_EcranTitre_bouton;
    private javax.swing.JLabel Titre_label;
    // End of variables declaration//GEN-END:variables
}
