/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tp_duo_mega_demineur;

/**
 *
 * @author Alexander
 */
public class Ecran_Défaite extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ecran_Défaite.class.getName());

    /**
     * Creates new form Ecran_Défaite
     */
    public Ecran_Défaite() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Défaite_label = new javax.swing.JLabel();
        Retour_EcranTitre_Défaite_bouton = new javax.swing.JButton();
        RelancerPartie_Défaite_bouton = new javax.swing.JButton();
        QuitterDéfaite_bouton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Défaite_label.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        Défaite_label.setText("Défaite...");

        Retour_EcranTitre_Défaite_bouton.setText("Ecran Titre");
        Retour_EcranTitre_Défaite_bouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Retour_EcranTitre_Défaite_boutonActionPerformed(evt);
            }
        });

        RelancerPartie_Défaite_bouton.setText("Relancer une partie");
        RelancerPartie_Défaite_bouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelancerPartie_Défaite_boutonActionPerformed(evt);
            }
        });

        QuitterDéfaite_bouton.setText("Quitter");
        QuitterDéfaite_bouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitterDéfaite_boutonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Défaite_label)
                .addGap(214, 214, 214))
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(Retour_EcranTitre_Défaite_bouton)
                .addGap(94, 94, 94)
                .addComponent(RelancerPartie_Défaite_bouton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(QuitterDéfaite_bouton)
                .addGap(84, 84, 84))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(Défaite_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 218, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Retour_EcranTitre_Défaite_bouton)
                    .addComponent(RelancerPartie_Défaite_bouton)
                    .addComponent(QuitterDéfaite_bouton))
                .addGap(102, 102, 102))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Retour_EcranTitre_Défaite_boutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Retour_EcranTitre_Défaite_boutonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Retour_EcranTitre_Défaite_boutonActionPerformed

    private void RelancerPartie_Défaite_boutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelancerPartie_Défaite_boutonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RelancerPartie_Défaite_boutonActionPerformed

    private void QuitterDéfaite_boutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitterDéfaite_boutonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuitterDéfaite_boutonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Ecran_Défaite().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Défaite_label;
    private javax.swing.JButton QuitterDéfaite_bouton;
    private javax.swing.JButton RelancerPartie_Défaite_bouton;
    private javax.swing.JButton Retour_EcranTitre_Défaite_bouton;
    // End of variables declaration//GEN-END:variables
}
