/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tp_duo_mega_demineur;

/**
 *
 * @author Alexander
 */
public class Ecran_Jeu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ecran_Jeu.class.getName());

    /**
     * Creates new form Ecran_Jeu
     */
    public Ecran_Jeu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Retour_EcranTitre_Jeu_bouton = new javax.swing.JButton();
        Relancer_Jeu_bouton = new javax.swing.JButton();
        Quitter_Jeu_bouton = new javax.swing.JButton();
        Titre_Jeu_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Retour_EcranTitre_Jeu_bouton.setText("Ecran Titre");
        Retour_EcranTitre_Jeu_bouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Retour_EcranTitre_Jeu_boutonActionPerformed(evt);
            }
        });

        Relancer_Jeu_bouton.setText("Relancer");
        Relancer_Jeu_bouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Relancer_Jeu_boutonActionPerformed(evt);
            }
        });

        Quitter_Jeu_bouton.setText("Quitter");
        Quitter_Jeu_bouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Quitter_Jeu_boutonActionPerformed(evt);
            }
        });

        Titre_Jeu_label.setFont(new java.awt.Font("Snap ITC", 1, 48)); // NOI18N
        Titre_Jeu_label.setText("JEU");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(269, 269, 269)
                .addComponent(Titre_Jeu_label)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(Retour_EcranTitre_Jeu_bouton)
                .addGap(157, 157, 157)
                .addComponent(Relancer_Jeu_bouton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                .addComponent(Quitter_Jeu_bouton)
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(Titre_Jeu_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 275, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Relancer_Jeu_bouton)
                    .addComponent(Retour_EcranTitre_Jeu_bouton)
                    .addComponent(Quitter_Jeu_bouton))
                .addGap(81, 81, 81))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Retour_EcranTitre_Jeu_boutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Retour_EcranTitre_Jeu_boutonActionPerformed
        // TODO add your handling code here:
        Ecran_Titre accueil = new Ecran_Titre();
        accueil.setLocationRelativeTo(this); 
        accueil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Retour_EcranTitre_Jeu_boutonActionPerformed

    private void Relancer_Jeu_boutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Relancer_Jeu_boutonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Relancer_Jeu_boutonActionPerformed

    private void Quitter_Jeu_boutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Quitter_Jeu_boutonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_Quitter_Jeu_boutonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Ecran_Jeu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Quitter_Jeu_bouton;
    private javax.swing.JButton Relancer_Jeu_bouton;
    private javax.swing.JButton Retour_EcranTitre_Jeu_bouton;
    private javax.swing.JLabel Titre_Jeu_label;
    // End of variables declaration//GEN-END:variables
}
