/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tp_duo_mega_demineur;

/**
 *
 * @author Alexander
 */
public class Ecran_Victoire extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ecran_Victoire.class.getName());

    /**
     * Creates new form Ecran_Victoire
     */
    public Ecran_Victoire() {
        initComponents();
        setImageToLabelKeepRatio(YouDroppedThis_label, "/Images/YouDroppedThis.jpg");
    }
    private void setImageToLabelKeepRatio(javax.swing.JLabel label, String resourcePath) {
        java.net.URL url = getClass().getResource(resourcePath);
        if (url == null) {
            System.err.println("Ressource introuvable : " + resourcePath);
            return;
        }
        javax.swing.ImageIcon originalIcon = new javax.swing.ImageIcon(url);
        if (label.getWidth() <= 0 || label.getHeight() <= 0) {
            label.setIcon(originalIcon); // icône provisoire
            label.addComponentListener(new java.awt.event.ComponentAdapter() {
                @Override
                public void componentResized(java.awt.event.ComponentEvent e) {
                    scaleAndSetIconKeepRatio(label, originalIcon);
                }
                @Override
                public void componentShown(java.awt.event.ComponentEvent e) {
                    scaleAndSetIconKeepRatio(label, originalIcon);
                }
            });
            return;
        }
        scaleAndSetIconKeepRatio(label, originalIcon);
    }
    private void scaleAndSetIconKeepRatio(javax.swing.JLabel label, javax.swing.ImageIcon originalIcon) {
        int labelW = label.getWidth();
        int labelH = label.getHeight();
        if (labelW <= 0 || labelH <= 0) {
            return;
        }
        int imgW = originalIcon.getIconWidth();
        int imgH = originalIcon.getIconHeight();
        double scale = Math.min((double) labelW / imgW, (double) labelH / imgH);
        int newW = Math.max(1, (int) (imgW * scale));
        int newH = Math.max(1, (int) (imgH * scale));
        java.awt.Image scaled = originalIcon.getImage()
                .getScaledInstance(newW, newH, java.awt.Image.SCALE_SMOOTH);
        label.setIcon(new javax.swing.ImageIcon(scaled));
        label.setText("");
        label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Victoire_label = new javax.swing.JLabel();
        Retour_EcranTitre_Victoire_bouton = new javax.swing.JButton();
        QuitterVictoire_bouton = new javax.swing.JButton();
        YouDroppedThis_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Victoire_label.setFont(new java.awt.Font("Papyrus", 1, 48)); // NOI18N
        Victoire_label.setText("Victoire !");
        getContentPane().add(Victoire_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, -1, -1));

        Retour_EcranTitre_Victoire_bouton.setText("Ecran Titre");
        Retour_EcranTitre_Victoire_bouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Retour_EcranTitre_Victoire_boutonActionPerformed(evt);
            }
        });
        getContentPane().add(Retour_EcranTitre_Victoire_bouton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, -1, -1));

        QuitterVictoire_bouton.setText("Quitter");
        QuitterVictoire_bouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitterVictoire_boutonActionPerformed(evt);
            }
        });
        getContentPane().add(QuitterVictoire_bouton, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 460, -1, -1));

        YouDroppedThis_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/YouDropThis.jpg"))); // NOI18N
        YouDroppedThis_label.setText("YouDropThis_label");
        getContentPane().add(YouDroppedThis_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 280, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Retour_EcranTitre_Victoire_boutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Retour_EcranTitre_Victoire_boutonActionPerformed
        // TODO add your handling code here:
        Ecran_Titre accueil = new Ecran_Titre();
        accueil.setLocationRelativeTo(this); 
        accueil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Retour_EcranTitre_Victoire_boutonActionPerformed

    private void QuitterVictoire_boutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitterVictoire_boutonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_QuitterVictoire_boutonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Ecran_Victoire().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton QuitterVictoire_bouton;
    private javax.swing.JButton Retour_EcranTitre_Victoire_bouton;
    private javax.swing.JLabel Victoire_label;
    private javax.swing.JLabel YouDroppedThis_label;
    // End of variables declaration//GEN-END:variables
}
